//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2013.12.26 at 09:04:27 PM CET 
//


package it.mexican.plugin.model;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="archetypes">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="archetype" maxOccurs="unbounded">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="groupId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="artifactId" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="version" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="repository" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                             &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {"archetypes"})
@XmlRootElement(name = "archetype-catalog")
public class ArchetypeCatalog {

    @XmlElement(required = true)
    protected ArchetypeCatalog.Archetypes archetypes;

    /**
     * Gets the value of the archetypes property.
     * 
     * @return
     *     possible object is
     *     {@link ArchetypeCatalog.Archetypes }
     *     
     */
    public ArchetypeCatalog.Archetypes getArchetypes() {
        return archetypes;
    }

    /**
     * Sets the value of the archetypes property.
     * 
     * @param value
     *     allowed object is
     *     {@link ArchetypeCatalog.Archetypes }
     *     
     */
    public void setArchetypes(ArchetypeCatalog.Archetypes value) {
        this.archetypes = value;
    }


    /**
     * <p>Java class for anonymous complex type.
     * 
     * <p>The following schema fragment specifies the expected content contained within this class.
     * 
     * <pre>
     * &lt;complexType>
     *   &lt;complexContent>
     *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *       &lt;sequence>
     *         &lt;element name="archetype" maxOccurs="unbounded">
     *           &lt;complexType>
     *             &lt;complexContent>
     *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
     *                 &lt;sequence>
     *                   &lt;element name="groupId" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="artifactId" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="version" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="repository" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                   &lt;element name="description" type="{http://www.w3.org/2001/XMLSchema}string"/>
     *                 &lt;/sequence>
     *               &lt;/restriction>
     *             &lt;/complexContent>
     *           &lt;/complexType>
     *         &lt;/element>
     *       &lt;/sequence>
     *     &lt;/restriction>
     *   &lt;/complexContent>
     * &lt;/complexType>
     * </pre>
     * 
     * 
     */
    @XmlAccessorType(XmlAccessType.FIELD)
    @XmlType(name = "", propOrder = {"archetype"})
    public static class Archetypes {

        @XmlElement(required = true)
        protected List<it.mexican.plugin.model.Archetype> archetype;

        /**
         * Gets the value of the archetype property.
         * 
         * <p>
         * This accessor method returns a reference to the live list,
         * not a snapshot. Therefore any modification you make to the
         * returned list will be present inside the JAXB object.
         * This is why there is not a <CODE>set</CODE> method for the archetype property.
         * 
         * <p>
         * For example, to add a new item, do as follows:
         * <pre>
         *    getArchetype().add(newItem);
         * </pre>
         * 
         * 
         * <p>
         * Objects of the following type(s) are allowed in the list
         * {@link ArchetypeCatalog.Archetypes.Archetype }
         * 
         * 
         */
        public List<it.mexican.plugin.model.Archetype> getArchetype() {
            if (archetype == null) {
                archetype = new ArrayList<it.mexican.plugin.model.Archetype>();
            }
            return this.archetype;
        }
    }
}
